// Generated by CoffeeScript 1.6.3
var anymatch, anysort, splice;

anymatch = require('anymatch');

anysort = function(criteria, a, b) {
  var hasA, hasB, indexOfA, indexOfB, matcher, _ref;
  matcher = anymatch.matcher(criteria);
  indexOfA = matcher(a, true);
  indexOfB = matcher(b, true);
  _ref = [indexOfA !== -1, indexOfB !== -1], hasA = _ref[0], hasB = _ref[1];
  if (hasA && !hasB) {
    return -1;
  } else if (!hasA && hasB) {
    return 1;
  } else if (hasA && hasB) {
    return indexOfA - indexOfB;
  } else {
    return 0;
  }
};

anysort.match = anymatch;

anysort.matcher = anymatch.matcher;

anysort.splice = splice = function(criteria, array) {
  var matched, matcher, unmatched;
  matcher = anymatch.matcher(criteria);
  matched = array.filter(matcher);
  unmatched = array.filter(function(s) {
    return -1 === matched.indexOf(s);
  });
  matched = matched.sort(function(a, b) {
    return anysort(criteria, a, b);
  });
  return {
    matched: matched,
    unmatched: unmatched,
    sorted: matched.concat(unmatched)
  };
};

anysort.grouped = function(groups, array) {
  var after, before, remaining, sorted;
  sorted = [];
  before = null;
  after = [];
  remaining = array.slice();
  groups.forEach(function(criteria) {
    var matched, unmatched, _ref;
    if (criteria === 'unmatched') {
      before = sorted.slice();
      return sorted = [];
    }
    _ref = splice(criteria, remaining), matched = _ref.matched, unmatched = _ref.unmatched;
    sorted = sorted.concat(matched);
    return remaining = unmatched;
  });
  if (before) {
    after = sorted;
  } else {
    before = sorted;
  }
  return before.concat(remaining.sort(), after);
};

module.exports = anysort;
